name: e2e
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
        run: npm i    
        run: npm run start
        run: npm run cypress:run
      # https://github.com/cypress-io/github-action
     
         
          