name: main
on: [push]

jobs:
  build-and-test-node12:
    runs-on: ubuntu-20.04
    name: CI 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - run: npm run format
      - run: npm run build
      - run: npm test
      - run: npm run check:markdown