name: CI
on:
  pull_request: null
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        uses: actions/setup-node@v2
      - name: Installation of dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  api-tests-and-report:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js 10 setup
        uses: actions/setup-node@v2
        
     
   